package entities;
// Generated 14-jul-2015 18:23:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name="brand"
    ,catalog="test"
)
public class Brand  implements java.io.Serializable {


     private String name;
     private String country;
     private Set<Model> models = new HashSet<Model>(0);

    public Brand() {
    }

	
    public Brand(String name) {
        this.name = name;
    }
    public Brand(String name, String country, Set<Model> models) {
       this.name = name;
       this.country = country;
       this.models = models;
    }
   
     @Id 

    
    @Column(name="name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="country", length=100)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="brand")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


